### ISSUE TITLE
The LibreOffice icons shouldn't have the seagulls

### ISSUE THREAD

**Issue by fitojb** [dangvd/crystal-remix-icon-theme#5]
Consider refreshing the icons adding the "dog-ear" triangle and removing the old OOo seagulls :)

**Comment by dangvd** [comment]
Hi,

Thanks for pointing it out.

Unfortunately in the original Crystal icon sets there is no "dog-ear" Libre Office icons, so I have to make do with the Open Office ones. I'm not a graphics designer so I don't think I can make new ones myself.

Viet

**Comment by dangvd** [comment]
Closing as not fixable.
