### ISSUE TITLE
Giant icons in GTK applications

### ISSUE THREAD

**Issue by ghost** [dangvd/crystal-remix-icon-theme#6]
![2023-06-13_11-06](https://github.com/dangvd/crystal-remix-icon-theme/assets/96852907/bce90372-fd1d-404a-973f-3c0fb44b9276)

Qt applications have regular sized icons, but GTK2 and GTK3+ use a giant version of them. Setting the icon sizes in ~/.gtkrc-2.0 and ~/.config/gtk-3.0/settings.ini did not work. The theme used, TraditionalOk, does not seem to override these either.

**Comment by dangvd** [comment]
Sorry for the delay. It should look better now with the added 32px icons.

**Comment by dangvd** [comment]
Closing as it's fixed in v2.0.

**Comment by Impeta** [comment]
@dangvd Are you sure it's fixed? It's still prevalent on my end. Latest version, v2.1, still can reproduce it. 
![Screenshot_20240527_213313](https://github.com/dangvd/crystal-remix-icon-theme/assets/105376276/804ad613-187e-4732-8b8f-44a362534bb4)

**Comment by dangvd** [comment]
Ah sorry, seems I need to add more small size icons. Will look at it.

**Comment by dangvd** [comment]
This should be fixed on the main branch now. I'll release a new version soon, after a few more minor fixes.

**Comment by dangvd** [comment]
Fixed in version 2.2 released today.
